name: PluginUtils
main: com.mcmiddleearth.pluginutil.PluginUtilsPlugin
version: 1.1.0
author: Eriol_Eandur
load: STARTUP
softdepend: [ProtocolLib,Essentials]

commands:
    dev:
        description: manage debub output
        usage: /dev [true | false | r]
    
permission:
    pluginutil.developer:
        description: Gives access to all plotbuild commands
        default: op
