name: ${project.artifactId}
main: com.mcmiddleearth.pluginutil.PluginUtilsPlugin
version: ${project.version}
author: Eriol_Eandur
load: STARTUP
softdepend: [ProtocolLib,Essentials,WorldEdit]
api-version: 1.16

commands:
    dev:
        description: manage debub output
        usage: /dev [true | false | r]
    
permission:
    pluginutil.developer:
        description: Gives access to all plotbuild commands
        default: op
